name: Build UnityPy for Pyodide

on:
  push:
  workflow_dispatch:

jobs:
  build_pyodide_wheels:
    name: Build pyodide wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        env:
          CIBW_PLATFORM: pyodide

      - uses: actions/upload-artifact@v7
        with:
          name: "pyodide-wheels"
          path: ./wheelhouse/*.whl
