name: Build UnityPy dependencies for Pyodide

on:
  push:
  workflow_dispatch:

jobs:
  build_pyodide_wheels:
    name: Build pyodide wheels for ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - { version: "3.12", filter: "cp312-*" }
          - { version: "3.13", filter: "cp312-*" }
        package:
          - { name: "archspec", version: "0.2.5", pure: true }
          - { name: "astc-encoder-py", version: "0.1.12" }
          - { name: "attrs", version: "26.1.0", pure: true }
          - { name: "brotli", version: "1.2.0" }
          - { name: "etcpak", version: "0.9.15" }
          - { name: "fmod_toolkit", version: "0.1.3" }
          - { name: "fsspec", version: "2026.3.0", pure: true }
          - { name: "lz4", version: "4.4.5" }
          - { name: "pillow", version: "12.2.0" }
          - { name: "pyfmodex", version: "0.7.2", pure: true }
          - { name: "texture2ddecoder", version: "1.0.6" }
          - { name: "TypeTreeGeneratorAPI", repo: "UnityPy-Org/TypeTreeGeneratorAPI", commit: "df79bd6a786d4ba52ed4a7b3d40047ecf578256b" }
          - { name: "UnityPy", version: "1.25.0" }

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Find sdist
        if: ${{ !matrix.package.repo }}
        env:
          PACKAGE_NAME: ${{ matrix.package.name }}
          PACKAGE_VERSION: ${{ matrix.package.version }}
        run: |
          mkdir -p build/${PACKAGE_NAME}
          export PACKAGE_SDIST_URL=`curl -L "https://pypi.org/pypi/${PACKAGE_NAME}/json" | jq -r ".releases.[\"${PACKAGE_VERSION}\"] | map(select(.packagetype == \"sdist\")) | .[0].url"`
          wget -O build/${PACKAGE_NAME}.tar.gz ${PACKAGE_SDIST_URL}
          tar -xf build/${PACKAGE_NAME}.tar.gz -C build/${PACKAGE_NAME} --strip-components 1

      - name: Clone repository
        if: ${{ matrix.package.repo }}
        uses: actions/checkout@v6
        with:
          repository: ${{ matrix.package.repo }}
          ref: ${{ matrix.package.commit }}
          path: build/${{ matrix.package.name }}

      - name: Build wheels as pure
        if: ${{ matrix.package.pure }}
        env:
          PACKAGE_NAME: ${{ matrix.package.name }}
          PACKAGE_VERSION: ${{ matrix.package.version }}
        run: |
          python -m pip wheel -w wheelhouse build/${PACKAGE_NAME}

      - name: Build wheels with cibuildwheel
        if: ${{ !matrix.package.pure }}
        uses: pypa/cibuildwheel@v3.4.1
        with:
            package-dir: build/${{ matrix.package.name }}
        env:
          CIBW_PLATFORM: pyodide
          CIBW_BUILD: ${{ matrix.python.filter }}

      - uses: actions/upload-artifact@v7
        with:
          name: "pyodide-${{ matrix.python.version }}-wheels"
          path: ./wheelhouse/*.whl
