name: Build UnityPy for Pyodide

on:
  push:
  workflow_dispatch:

jobs:
  build_pyodide_wheels:
    name: Build pyodide wheels for ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - { name: "archspec", version: "0.2.5" }
          - { name: "astc-encoder-py", version: "0.1.12" }
          - { name: "attrs", version: "26.1.0" }
          - { name: "brotli", version: "1.2.0" }
          - { name: "etcpak", version: "0.9.15" }
          - { name: "fmod_toolkit", version: "0.1.3" }
          - { name: "fsspec", version: "2026.3.0" }
          - { name: "lz4", version: "4.4.5" }
          - { name: "pillow", version: "12.2.0" }
          - { name: "pyfmodex", version: "0.7.2" }
          - { name: "texture2ddecoder", version: "1.0.6" }
          - { name: "TypeTreeGeneratorAPI", version: "0.0.10" }
          - { name: "UnityPy", version: "1.25.0" }

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install yq
        run: |
          pip install yq

      - name: Find sdist
        env:
          PACKAGE_NAME: ${{ matrix.package.name }}
          PACKAGE_VERSION: ${{ matrix.package.version }}
        run: |
          mkdir -p build/${PACKAGE_NAME}
          export PACKAGE_SDIST_URL=`curl -L "https://pypi.org/pypi/${PACKAGE_NAME}/json" | jq -r ".releases.[\"${PACKAGE_VERSION}\"] | map(select(.packagetype == \"sdist\")) | .[0].url"`
          wget -O build/${PACKAGE_NAME}.tar.gz ${PACKAGE_SDIST_URL}
          tar -xf build/${PACKAGE_NAME}.tar.gz -C build/${PACKAGE_NAME} --strip-components 1

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        with:
            package-dir: build/${{ matrix.package.name }}
        env:
          CIBW_PLATFORM: pyodide

      - uses: actions/upload-artifact@v7
        with:
          name: "pyodide-${{ matrix.package.name }}-wheels"
          path: ./wheelhouse/*.whl
